### PR TITLE
create_unsigned_tx from inputs

### PR DESCRIPTION
**Pull request by d42**
blatantly stolen from #31 but with tests

### CODE REVIEW

**Comment by quentinlesceller** [comment]
Any chance you could merge master into it so the new CI can work?

**Comment by d42** [comment]
@quentinlesceller i've rebased on master, is there anything more that needs to be done? :^)

**Comment by quentinlesceller** [comment]
Okay give me a sec I need to fix the trigger for the CI.

**Comment by quentinlesceller** [comment]
Okay can you merge master again?

**Comment by d42** [comment]
@quentinlesceller done

**Comment by quentinlesceller** [comment]
Hum okay I was under the impression the secret could be used by forked repository but that make sense it doesn't work. Will run the tests locally.

**Pull request merged**
