### PR TITLE
fix for null-data not needing an address assertion

### PR DESCRIPTION
**Pull request by acityinohio**
A customer was trying to use the create_unsigned_tx function to add a null-data output, and in the process of debugging I realized it was being a bit aggressive on assertions. Thanks to @hbcheng for helping me come up with this fix!

### CODE REVIEW

**Comment by mflaxman** [comment]
I love seeing you write python @acityinohio! Can you add a test that covers this change? It appears all old tests are passing (good!), but I'd like coverage of whatever you add.

**Comment by acityinohio** [comment]
Heh, since I'm normally a Gopher, it's nice to dust off my mind's pythonic cobwebs from time to time. 😄 I added some tests, but I had to change the way TX verification works...let me know if my changes make sense/feel free to merge if they do!

**Comment by mflaxman** [comment]
Merged, thanks. Will have to push an update to pypi on my home computer this weekend, but at least anyone who wants it can pull it from github for now.

**Comment by mflaxman** [comment]
done: https://pypi.python.org/pypi/blockcypher/

**Pull request merged**
