### PR TITLE
FIRST4_MKEY_CS_MAPPINGS_UPPER as a dictionary of sets, so xpubs are v…

### PR DESCRIPTION
**Pull request by d42**
…alid for both dash and btc

#61

### CODE REVIEW

**Comment by quentinlesceller** [comment]
Thanks for the PR @d42. I'll take a look in a bit.

**Comment by d42** [comment]
@quentinlesceller also consider #78

**Comment by quentinlesceller** [comment]
Tests are currently failing.
See below:
```
❯ python test_blockcypher.py
.......Generating private key details server-side. You really should do this client-side. See https://github.com/sbuss/bitmerchant for an example.
Generating private key details server-side. You really should do this client-side. See https://github.com/sbuss/bitmerchant for an example.
Generating private key details server-side. You really should do this client-side. See https://github.com/sbuss/bitmerchant for an example.
Generating private key details server-side. You really should do this client-side. See https://github.com/sbuss/bitmerchant for an example.
......E
======================================================================
ERROR: test_register_btc_wallet (__main__.RegisterHDWallet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_blockcypher.py", line 517, in test_register_btc_wallet
    is_hd_wallet=True)
  File "/Users/quentin/blockcypher/blockcypher-python/blockcypher/api.py", line 1268, in delete_wallet
    url = make_url(coin_symbol, wallet)
  File "/Users/quentin/blockcypher/blockcypher-python/blockcypher/api.py", line 1862, in make_url
    url = urljoin(*url_bits)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'dict' object has no attribute 'startswith'

----------------------------------------------------------------------
Ran 14 tests in 15.410s

FAILED (errors=1)

~/blockcypher/blockcypher-python remotes/d42/hdwallet-prefix 15s
❯ python3 test_blockcypher.py
.......Generating private key details server-side. You really should do this client-side. See https://github.com/sbuss/bitmerchant for an example.
Generating private key details server-side. You really should do this client-side. See https://github.com/sbuss/bitmerchant for an example.
Generating private key details server-side. You really should do this client-side. See https://github.com/sbuss/bitmerchant for an example.
Generating private key details server-side. You really should do this client-side. See https://github.com/sbuss/bitmerchant for an example.
......E
======================================================================
ERROR: test_register_btc_wallet (__main__.RegisterHDWallet)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_blockcypher.py", line 517, in test_register_btc_wallet
    is_hd_wallet=True)
  File "/Users/quentin/blockcypher/blockcypher-python/blockcypher/api.py", line 1268, in delete_wallet
    url = make_url(coin_symbol, wallet)
  File "/Users/quentin/blockcypher/blockcypher-python/blockcypher/api.py", line 1862, in make_url
    url = urljoin(*url_bits)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'dict'

----------------------------------------------------------------------
Ran 14 tests in 3.299s

FAILED (errors=1)
```

**Comment by d42** [comment]
@quentinlesceller it should be based on #78 , i've rebased it, also i find using posixpath.join instead of urllib quite curious

**Comment by quentinlesceller** [comment]
Python 2 and 3 tests stil aren't passing. Regarding the `posixpath.join` it's just a python2/3 compatible replacement of os.path.join that also works on windows.

**Comment by d42** [comment]
curious, it passes for me.

**Comment by d42** [comment]
:+1:

**Comment by quentinlesceller** [comment]
Will merge in a bit.

**Pull request merged**
