### PR TITLE
Accept later version of required packages

### PR DESCRIPTION
**Pull request by muneeb-ali**
Accept later version of required packages instead of forcing a particular version.

Trying to avoid this default behavior of pip where it uninstall later versions if there is a conflict :-) 

```
Found existing installation: requests 2.9.1
    Uninstalling requests-2.9.1:
      Successfully uninstalled requests-2.9.1
  Running setup.py install for python-dateutil
  Found existing installation: bitcoin 1.1.42
    Uninstalling bitcoin-1.1.42:
      Successfully uninstalled bitcoin-1.1.42
  Running setup.py install for bitcoin
  Running setup.py install for blockcypher
Successfully installed bitcoin-1.1.38 blockcypher-1.0.57 python-dateutil-2.2 requests-2.4.3
```

### CODE REVIEW

**Comment by mflaxman** [comment]
Hey @muneeb-ali , thanks for the PR! I actually originally got feedback from your coworker @shea256 on how to structure this library.

Unfortunately, this PR appears to break the units tests. This is my concern with allowing multiple versions, something that seems innocuous could cause a problem. I think for most libraries that risk is probably ok, but for something that handles bitcoin transaction signing and address generation it's too risky.

That said, your point does seem quite fair. Why force a particular version of the innocuous (and popular) requests library for example?

Can I ask why is this a problem for you? I deploy all of my production code in virtual environments and my understanding is that this is the best practice. The problem you're describing only seems like a problem if you're not using a virtual environment.

**Comment by muneeb-ali** [comment]
I mainly wanted to switch to bitcoin==1.1.39 because there is an issue with signing multiple unsigned inputs that was resolved in that version.

Here is a situation, where ----> denotes "required":

packageA  ----> packageB, packageC 

packageB ----> bitcoin==1.1.39
packageC ----> bitcoin==1.1.38

In the above scenario because pip install packageC after installing packageB, it uninstalls bitcoin 1.1.39 and (re-)installs bitcoin 1.1.38. 

Maybe there is a better work-around, but I thought I'd try to get you guys to update the bitcoin package version. Totally makes sense to not allow just any version but only allow a *specific* version.

The unit tests seem to pass with 1.1.39.

Hope all is well :-)

**Comment by mflaxman** [comment]
@muneeb-ali that does make sense and I see where you're coming from. Thanks!

I'm generally vary wary of allowing multiple versions of the libraries to be used, because if there is a bug for a user it will be hard to track down. pybitcointools is not that well maintained (lots of open bug reports and PRs languish), we once ran into a problem where the library was very late to adopt BIP66 compliant signatures for example and had to fork it. Also, that library does not follow best practices (see heavy usage of `import *`, or functions with ambiguous names and no docstrings, one letter variables with no comment describing what they do, etc) so I'm just not comfortable with an open-ended dependency on future (untested versions).

This change seems to work, is that sufficient? Travis CI is not behaving 100% as I expected (they also had downtime when you originally pushed this), so I want to double-check to be sure that this does in fact work as it seems to.

**Comment by mflaxman** [comment]
Sorry for the delay @muneeb-ali, this is now live!

**Comment by muneeb-ali** [comment]
Awesome, thanks! And this conversation actually made us switch to using exact package numbers in [Blockstore](https://github.com/blockstack/blockstore/blob/v0.0.10/setup.py) as well

**Pull request merged**
