### PR TITLE
Feat: Added dash compatibility

### PR DESCRIPTION
**Pull request by Alex-Werner**
Added Dash constants

### CODE REVIEW

**Comment by l0rb** [comment]
+1
please merge this commit. dash support in the python lib is much needed

**Comment by Alex-Werner** [comment]
Is there anything I can do to unblock this P.R ?

**Comment by hbcheng** [comment]
Hey @Alex-Werner, this looks good to me, merging. Will try to get travis working again in the meantime. 

While I'll go ahead a merge now, a trivial test (say, fetching the main chain endpoint at http://api.blockcypher.com/v1/dash/main) in `test_blockcypher.py` would be an appreciated follow-up.

**Comment by hbcheng** [comment]
Looks like Travis is because of this: https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

All tests passed on my local machine and on Travis on master.

**Comment by Alex-Werner** [comment]
@hbcheng Hum. I hoped I had do that already... Actually this is indeed my mistake. 
I will add it in another P.R before next monday. 
Thanks :)

**Pull request merged**
